/* 
 * INET 3101 - AI Code Audit Starter Code
 * Flawed implementation of to_base_n generated by LLM
 */

#include <stdio.h>

void to_base_n(int num, int base) {
    // BUG 1: Missing bounds check (valid bases are 2 through 16)
    static int first_call = 1;

    if (base < 2 || base > 16) {
        printf("Error: base must be between 2 and 16.");
        return;
    }

    // BUG 4: Edge cases
    if (num == 0) {
        printf("0");
        first_call = 1;
        return;
    }

    // BUG 3: Prefix formatting
    if (first_call) {
        if (base == 8) {
            printf("g0");
        } else if (base == 16) {
            printf("g0x");
        }

        first_call = 0;
    }

    int r = num % base;
    
    if (num >= base) {
        to_base_n(num / base, base);
    }
    
    // BUG 2: Digits >= 10 print as numbers (e.g., 10 instead of 'a')
    if (r >= 10) {
        printf("%c", 'a' + (r - 10));
    } else {
        printf("%d", r);
    }

    // Reset for next independent call
    first_call = 1;
}

int main(void) {
    printf("Testing Base 8 (21): ");
    to_base_n(21, 8); // Expected: g025
    printf("\n");
    
    printf("Testing Base 16 (129): ");
    to_base_n(129, 16); // Expected: 0x81 | Actual: 1281
    printf("\n");

    printf("Testing Invalid Base (129, 20): ");
    to_base_n(129, 20); // Expected: Error message | Actual: Invalid output
    printf("\n");

    return 0;
}